// <auto-generated />
using System;
using Chronicis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chronicis.Api.Migrations
{
    [DbContext(typeof(ChronicisDbContext))]
    [Migration("20251230200922_AddUserOnboardingFlag")]
    partial class AddUserOnboardingFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chronicis.Shared.Models.Arc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AISummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AISummaryGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("SummaryCustomPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SummaryIncludeWebSources")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SummaryTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SummaryTemplateId");

                    b.HasIndex("CampaignId", "SortOrder");

                    b.ToTable("Arcs");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AISummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AISummaryGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconEmoji")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InGameDate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SummaryCustomPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SummaryIncludeWebSources")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SummaryTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArcId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LastModifiedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SummaryTemplateId");

                    b.HasIndex("Title");

                    b.HasIndex("Type");

                    b.HasIndex("WorldId");

                    b.HasIndex("ParentId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Articles_ParentId_Slug")
                        .HasFilter("[ParentId] IS NOT NULL");

                    b.HasIndex("WorldId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Articles_WorldId_Slug_Root")
                        .HasFilter("[ParentId] IS NULL");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SourceArticleId");

                    b.HasIndex("TargetArticleId");

                    b.HasIndex("SourceArticleId", "TargetArticleId", "Position")
                        .IsUnique();

                    b.ToTable("ArticleLinks");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AISummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AISummaryGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SummaryCustomPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SummaryIncludeWebSources")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SummaryTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SummaryTemplateId");

                    b.HasIndex("WorldId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.CampaignMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CharacterName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CampaignId", "UserId")
                        .IsUnique();

                    b.ToTable("CampaignMembers");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.SummaryTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsSystem");

                    b.HasIndex("WorldId");

                    b.ToTable("SummaryTemplates");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("HasCompletedOnboarding")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Auth0UserId")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("OwnerId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Worlds_OwnerId_Slug");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("WorldLinks");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Arc", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Campaign", "Campaign")
                        .WithMany("Arcs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedArcs")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.SummaryTemplate", "SummaryTemplate")
                        .WithMany()
                        .HasForeignKey("SummaryTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");

                    b.Navigation("Creator");

                    b.Navigation("SummaryTemplate");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Article", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Arc", "Arc")
                        .WithMany("Sessions")
                        .HasForeignKey("ArcId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.Campaign", "Campaign")
                        .WithMany("Articles")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedArticles")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.User", "Modifier")
                        .WithMany("ModifiedArticles")
                        .HasForeignKey("LastModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.Article", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.User", "Player")
                        .WithMany("OwnedCharacters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.SummaryTemplate", "SummaryTemplate")
                        .WithMany()
                        .HasForeignKey("SummaryTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Articles")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Arc");

                    b.Navigation("Campaign");

                    b.Navigation("Creator");

                    b.Navigation("Modifier");

                    b.Navigation("Parent");

                    b.Navigation("Player");

                    b.Navigation("SummaryTemplate");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleLink", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Article", "SourceArticle")
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("SourceArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.Article", "TargetArticle")
                        .WithMany("IncomingLinks")
                        .HasForeignKey("TargetArticleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceArticle");

                    b.Navigation("TargetArticle");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Campaign", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Owner")
                        .WithMany("OwnedCampaigns")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.SummaryTemplate", "SummaryTemplate")
                        .WithMany()
                        .HasForeignKey("SummaryTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Campaigns")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("SummaryTemplate");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.CampaignMember", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Campaign", "Campaign")
                        .WithMany("Members")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.User", "User")
                        .WithMany("CampaignMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.SummaryTemplate", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Creator");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.World", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Owner")
                        .WithMany("OwnedWorlds")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldLink", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Links")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Arc", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Article", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("IncomingLinks");

                    b.Navigation("OutgoingLinks");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Campaign", b =>
                {
                    b.Navigation("Arcs");

                    b.Navigation("Articles");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.User", b =>
                {
                    b.Navigation("CampaignMemberships");

                    b.Navigation("CreatedArcs");

                    b.Navigation("CreatedArticles");

                    b.Navigation("ModifiedArticles");

                    b.Navigation("OwnedCampaigns");

                    b.Navigation("OwnedCharacters");

                    b.Navigation("OwnedWorlds");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.World", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Campaigns");

                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
