// <auto-generated />
using System;
using Chronicis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chronicis.Api.Migrations
{
    [DbContext(typeof(ChronicisDbContext))]
    [Migration("20260429010114_UrlRestructure_SessionNoteSlugScope")]
    partial class UrlRestructure_SessionNoteSlugScope
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chronicis.Shared.Models.Arc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AISummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AISummaryGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrivateNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("SummaryCustomPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SummaryIncludeWebSources")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SummaryTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SummaryTemplateId");

                    b.HasIndex("CampaignId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Arcs_CampaignId_Slug");

                    b.HasIndex("CampaignId", "SortOrder");

                    b.ToTable("Arcs");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AISummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AISummaryGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconEmoji")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InGameDate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SummaryCustomPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SummaryIncludeWebSources")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SummaryTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArcId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LastModifiedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_Articles_SessionId")
                        .HasFilter("[SessionId] IS NOT NULL");

                    b.HasIndex("SummaryTemplateId");

                    b.HasIndex("Title");

                    b.HasIndex("Type");

                    b.HasIndex("WorldId");

                    b.HasIndex("ParentId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Articles_ParentId_Slug")
                        .HasFilter("[ParentId] IS NOT NULL");

                    b.HasIndex("SessionId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Articles_SessionId_Slug_SessionNote")
                        .HasFilter("[Type] = 11 AND [SessionId] IS NOT NULL");

                    b.HasIndex("WorldId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Articles_WorldId_Slug_RootNonSessionNote")
                        .HasFilter("[ParentId] IS NULL AND [Type] <> 11");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AliasText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AliasType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AliasText");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ArticleId", "AliasText")
                        .IsUnique()
                        .HasDatabaseName("IX_ArticleAliases_ArticleId_AliasText");

                    b.ToTable("ArticleAliases");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleExternalLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ArticleId", "Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_ArticleExternalLinks_ArticleId_Source_ExternalId");

                    b.ToTable("ArticleExternalLinks");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SourceArticleId");

                    b.HasIndex("TargetArticleId");

                    b.HasIndex("SourceArticleId", "TargetArticleId", "Position")
                        .IsUnique();

                    b.ToTable("ArticleLinks");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AISummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AISummaryGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrivateNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SummaryCustomPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SummaryIncludeWebSources")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SummaryTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SummaryTemplateId");

                    b.HasIndex("WorldId");

                    b.HasIndex("WorldId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Campaigns_WorldId_Slug");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.MapFeature", b =>
                {
                    b.Property<Guid>("MapFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("FeatureType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("GeometryBlobKey")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("GeometryETag")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("LinkedArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MapLayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("WorldMapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.HasKey("MapFeatureId");

                    b.HasIndex("LinkedArticleId");

                    b.HasIndex("MapLayerId");

                    b.HasIndex("WorldMapId");

                    b.ToTable("MapFeatures");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.MapLayer", b =>
                {
                    b.Property<Guid>("MapLayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ParentLayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("WorldMapId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MapLayerId");

                    b.HasIndex("ParentLayerId");

                    b.HasIndex("WorldMapId");

                    b.ToTable("MapLayers");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGmOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArcId")
                        .HasDatabaseName("IX_Quest_ArcId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ArcId", "Status")
                        .HasDatabaseName("IX_Quest_ArcId_Status");

                    b.HasIndex("ArcId", "UpdatedAt")
                        .HasDatabaseName("IX_Quest_ArcId_UpdatedAt");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.QuestUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_QuestUpdate_SessionId")
                        .HasFilter("[SessionId] IS NOT NULL");

                    b.HasIndex("QuestId", "CreatedAt")
                        .HasDatabaseName("IX_QuestUpdate_QuestId_CreatedAt");

                    b.ToTable("QuestUpdates");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ResourceProvider", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentationLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("License")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Code");

                    b.ToTable("ResourceProviders");

                    b.HasData(
                        new
                        {
                            Code = "srd",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "System Reference Document for D&D 5th Edition",
                            DocumentationLink = "https://open5e.com/api-docs",
                            IsActive = true,
                            License = "https://open5e.com/legal",
                            Name = "Open 5e API"
                        },
                        new
                        {
                            Code = "srd14",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "System Reference Document 5.1",
                            DocumentationLink = "https://www.dndbeyond.com/srd?srsltid=AfmBOooZgD0uD_hbmyYkHEvFJtDJzktTdIa_J_N2GRnkPQvGIZ4ZSeBO#SystemReferenceDocumentv51",
                            IsActive = true,
                            License = "https://opengamingfoundation.org/ogl.html",
                            Name = "SRD 2014"
                        },
                        new
                        {
                            Code = "srd24",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "System Reference Document 5.2.1",
                            DocumentationLink = "https://www.dndbeyond.com/srd?srsltid=AfmBOooZgD0uD_hbmyYkHEvFJtDJzktTdIa_J_N2GRnkPQvGIZ4ZSeBO#SystemReferenceDocumentv52",
                            IsActive = true,
                            License = "https://creativecommons.org/licenses/by/4.0/",
                            Name = "SRD 2024"
                        },
                        new
                        {
                            Code = "ros",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ruins of Symbaroum source material",
                            DocumentationLink = "https://freeleaguepublishing.com/games/ruins-of-symbaroum/",
                            IsActive = true,
                            License = "https://opengamingfoundation.org/ogl.html",
                            Name = "Ruins of Symbaroum"
                        });
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AiSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AiSummaryGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AiSummaryGeneratedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PrivateNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AiSummaryGeneratedByUserId");

                    b.HasIndex("ArcId")
                        .HasDatabaseName("IX_Sessions_ArcId");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Sessions_CreatedBy");

                    b.HasIndex("ArcId", "SessionDate")
                        .HasDatabaseName("IX_Sessions_ArcId_SessionDate");

                    b.HasIndex("ArcId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Sessions_ArcId_Slug");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.SessionNoteMapFeature", b =>
                {
                    b.Property<Guid>("SessionNoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MapFeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SessionNoteId", "MapFeatureId");

                    b.HasIndex("MapFeatureId");

                    b.ToTable("SessionNoteMapFeatures");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.SummaryTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsSystem");

                    b.HasIndex("WorldId");

                    b.ToTable("SummaryTemplates");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.TutorialPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PageTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("PageType")
                        .IsUnique();

                    b.ToTable("TutorialPages");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("HasCompletedOnboarding")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Auth0UserId")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTutorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PrivateNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Worlds_Slug");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("IX_WorldDocuments_ArticleId")
                        .HasFilter("[ArticleId] IS NOT NULL");

                    b.HasIndex("UploadedById");

                    b.HasIndex("WorldId");

                    b.ToTable("WorldDocuments");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WorldId", "IsActive");

                    b.ToTable("WorldInvitations");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("WorldLinks");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldMap", b =>
                {
                    b.Property<Guid>("WorldMapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BasemapBlobKey")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("BasemapContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BasemapOriginalFilename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorldMapId");

                    b.HasIndex("WorldId");

                    b.HasIndex("WorldId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_WorldMaps_WorldId_Slug");

                    b.ToTable("WorldMaps");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldMapArc", b =>
                {
                    b.Property<Guid>("WorldMapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArcId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorldMapId", "ArcId");

                    b.HasIndex("ArcId");

                    b.ToTable("WorldMapArcs");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldMapCampaign", b =>
                {
                    b.Property<Guid>("WorldMapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorldMapId", "CampaignId");

                    b.HasIndex("CampaignId");

                    b.ToTable("WorldMapCampaigns");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("UserId");

                    b.HasIndex("WorldId", "UserId")
                        .IsUnique();

                    b.ToTable("WorldMembers");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldResourceProvider", b =>
                {
                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceProviderCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LookupKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorldId", "ResourceProviderCode");

                    b.HasIndex("ResourceProviderCode");

                    b.HasIndex("WorldId");

                    b.HasIndex("WorldId", "LookupKey")
                        .IsUnique()
                        .HasDatabaseName("IX_WorldResourceProviders_WorldId_LookupKey")
                        .HasFilter("[LookupKey] IS NOT NULL");

                    b.ToTable("WorldResourceProviders");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Arc", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Campaign", "Campaign")
                        .WithMany("Arcs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedArcs")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.SummaryTemplate", "SummaryTemplate")
                        .WithMany()
                        .HasForeignKey("SummaryTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");

                    b.Navigation("Creator");

                    b.Navigation("SummaryTemplate");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Article", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Arc", "Arc")
                        .WithMany("SessionArticles")
                        .HasForeignKey("ArcId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.Campaign", "Campaign")
                        .WithMany("Articles")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedArticles")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.User", "Modifier")
                        .WithMany("ModifiedArticles")
                        .HasForeignKey("LastModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.Article", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.User", "Player")
                        .WithMany("OwnedCharacters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.Session", "Session")
                        .WithMany("SessionNotes")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chronicis.Shared.Models.SummaryTemplate", "SummaryTemplate")
                        .WithMany()
                        .HasForeignKey("SummaryTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Articles")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Arc");

                    b.Navigation("Campaign");

                    b.Navigation("Creator");

                    b.Navigation("Modifier");

                    b.Navigation("Parent");

                    b.Navigation("Player");

                    b.Navigation("Session");

                    b.Navigation("SummaryTemplate");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleAlias", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Article", "Article")
                        .WithMany("Aliases")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleExternalLink", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Article", "Article")
                        .WithMany("ExternalLinks")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleLink", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Article", "SourceArticle")
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("SourceArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.Article", "TargetArticle")
                        .WithMany("IncomingLinks")
                        .HasForeignKey("TargetArticleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceArticle");

                    b.Navigation("TargetArticle");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Campaign", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Owner")
                        .WithMany("OwnedCampaigns")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.SummaryTemplate", "SummaryTemplate")
                        .WithMany()
                        .HasForeignKey("SummaryTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Campaigns")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("SummaryTemplate");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.MapFeature", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Article", null)
                        .WithMany()
                        .HasForeignKey("LinkedArticleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chronicis.Shared.Models.MapLayer", null)
                        .WithMany()
                        .HasForeignKey("MapLayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.WorldMap", null)
                        .WithMany()
                        .HasForeignKey("WorldMapId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Chronicis.Shared.Models.MapLayer", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.MapLayer", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentLayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.WorldMap", "WorldMap")
                        .WithMany("Layers")
                        .HasForeignKey("WorldMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("WorldMap");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Quest", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Arc", "Arc")
                        .WithMany()
                        .HasForeignKey("ArcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedQuests")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arc");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.QuestUpdate", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedQuestUpdates")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.Quest", "Quest")
                        .WithMany("Updates")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.Session", "Session")
                        .WithMany("QuestUpdates")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Creator");

                    b.Navigation("Quest");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Session", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "AiSummaryGeneratedBy")
                        .WithMany()
                        .HasForeignKey("AiSummaryGeneratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.Arc", "Arc")
                        .WithMany("SessionEntities")
                        .HasForeignKey("ArcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedSessions")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiSummaryGeneratedBy");

                    b.Navigation("Arc");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.SessionNoteMapFeature", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.MapFeature", "MapFeature")
                        .WithMany("SessionNoteMapFeatures")
                        .HasForeignKey("MapFeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.Article", "SessionNote")
                        .WithMany("SessionNoteMapFeatures")
                        .HasForeignKey("SessionNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapFeature");

                    b.Navigation("SessionNote");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.SummaryTemplate", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Creator");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.TutorialPage", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.World", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Owner")
                        .WithMany("OwnedWorlds")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldDocument", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Article", "Article")
                        .WithMany("Images")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chronicis.Shared.Models.User", "UploadedBy")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Documents")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("UploadedBy");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldInvitation", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedInvitations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Invitations")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldLink", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Links")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldMap", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldMapArc", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Arc", "Arc")
                        .WithMany()
                        .HasForeignKey("ArcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.WorldMap", "WorldMap")
                        .WithMany("WorldMapArcs")
                        .HasForeignKey("WorldMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arc");

                    b.Navigation("WorldMap");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldMapCampaign", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.WorldMap", "WorldMap")
                        .WithMany("WorldMapCampaigns")
                        .HasForeignKey("WorldMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("WorldMap");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldMember", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Inviter")
                        .WithMany("InvitedMembers")
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.User", "User")
                        .WithMany("WorldMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Members")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inviter");

                    b.Navigation("User");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldResourceProvider", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.ResourceProvider", "ResourceProvider")
                        .WithMany("WorldResourceProviders")
                        .HasForeignKey("ResourceProviderCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("WorldResourceProviders")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceProvider");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Arc", b =>
                {
                    b.Navigation("SessionArticles");

                    b.Navigation("SessionEntities");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Article", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Children");

                    b.Navigation("ExternalLinks");

                    b.Navigation("Images");

                    b.Navigation("IncomingLinks");

                    b.Navigation("OutgoingLinks");

                    b.Navigation("SessionNoteMapFeatures");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Campaign", b =>
                {
                    b.Navigation("Arcs");

                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.MapFeature", b =>
                {
                    b.Navigation("SessionNoteMapFeatures");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.MapLayer", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Quest", b =>
                {
                    b.Navigation("Updates");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ResourceProvider", b =>
                {
                    b.Navigation("WorldResourceProviders");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Session", b =>
                {
                    b.Navigation("QuestUpdates");

                    b.Navigation("SessionNotes");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.User", b =>
                {
                    b.Navigation("CreatedArcs");

                    b.Navigation("CreatedArticles");

                    b.Navigation("CreatedInvitations");

                    b.Navigation("CreatedQuestUpdates");

                    b.Navigation("CreatedQuests");

                    b.Navigation("CreatedSessions");

                    b.Navigation("InvitedMembers");

                    b.Navigation("ModifiedArticles");

                    b.Navigation("OwnedCampaigns");

                    b.Navigation("OwnedCharacters");

                    b.Navigation("OwnedWorlds");

                    b.Navigation("UploadedDocuments");

                    b.Navigation("WorldMemberships");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.World", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Campaigns");

                    b.Navigation("Documents");

                    b.Navigation("Invitations");

                    b.Navigation("Links");

                    b.Navigation("Members");

                    b.Navigation("WorldResourceProviders");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldMap", b =>
                {
                    b.Navigation("Layers");

                    b.Navigation("WorldMapArcs");

                    b.Navigation("WorldMapCampaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
