// <auto-generated />
using System;
using Chronicis.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chronicis.Api.Migrations
{
    [DbContext(typeof(ChronicisDbContext))]
    partial class ChronicisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chronicis.Shared.Models.Arc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AISummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AISummaryGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("SummaryCustomPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SummaryIncludeWebSources")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SummaryTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SummaryTemplateId");

                    b.HasIndex("CampaignId", "SortOrder");

                    b.ToTable("Arcs");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AISummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AISummaryGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ArcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconEmoji")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("InGameDate")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SessionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SummaryCustomPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SummaryIncludeWebSources")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SummaryTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArcId");

                    b.HasIndex("CampaignId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LastModifiedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SummaryTemplateId");

                    b.HasIndex("Title");

                    b.HasIndex("Type");

                    b.HasIndex("WorldId");

                    b.HasIndex("ParentId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Articles_ParentId_Slug")
                        .HasFilter("[ParentId] IS NOT NULL");

                    b.HasIndex("WorldId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Articles_WorldId_Slug_Root")
                        .HasFilter("[ParentId] IS NULL");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AliasText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AliasType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AliasText");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ArticleId", "AliasText")
                        .IsUnique()
                        .HasDatabaseName("IX_ArticleAliases_ArticleId_AliasText");

                    b.ToTable("ArticleAliases");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleExternalLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ArticleId", "Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_ArticleExternalLinks_ArticleId_Source_ExternalId");

                    b.ToTable("ArticleExternalLinks");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TargetArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SourceArticleId");

                    b.HasIndex("TargetArticleId");

                    b.HasIndex("SourceArticleId", "TargetArticleId", "Position")
                        .IsUnique();

                    b.ToTable("ArticleLinks");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AISummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AISummaryGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SummaryCustomPrompt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SummaryIncludeWebSources")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SummaryTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SummaryTemplateId");

                    b.HasIndex("WorldId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArcId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGmOnly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArcId")
                        .HasDatabaseName("IX_Quest_ArcId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ArcId", "Status")
                        .HasDatabaseName("IX_Quest_ArcId_Status");

                    b.HasIndex("ArcId", "UpdatedAt")
                        .HasDatabaseName("IX_Quest_ArcId_UpdatedAt");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.QuestUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_QuestUpdate_SessionId");

                    b.HasIndex("QuestId", "CreatedAt")
                        .HasDatabaseName("IX_QuestUpdate_QuestId_CreatedAt");

                    b.ToTable("QuestUpdates");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ResourceProvider", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentationLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("License")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Code");

                    b.ToTable("ResourceProviders");

                    b.HasData(
                        new
                        {
                            Code = "srd",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "System Reference Document for D&D 5th Edition",
                            DocumentationLink = "https://open5e.com/api-docs",
                            IsActive = true,
                            License = "https://open5e.com/legal",
                            Name = "Open 5e API"
                        },
                        new
                        {
                            Code = "srd14",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "System Reference Document 5.1",
                            DocumentationLink = "https://www.dndbeyond.com/srd?srsltid=AfmBOooZgD0uD_hbmyYkHEvFJtDJzktTdIa_J_N2GRnkPQvGIZ4ZSeBO#SystemReferenceDocumentv51",
                            IsActive = true,
                            License = "https://opengamingfoundation.org/ogl.html",
                            Name = "SRD 2014"
                        },
                        new
                        {
                            Code = "srd24",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "System Reference Document 5.2.1",
                            DocumentationLink = "https://www.dndbeyond.com/srd?srsltid=AfmBOooZgD0uD_hbmyYkHEvFJtDJzktTdIa_J_N2GRnkPQvGIZ4ZSeBO#SystemReferenceDocumentv52",
                            IsActive = true,
                            License = "https://creativecommons.org/licenses/by/4.0/",
                            Name = "SRD 2024"
                        },
                        new
                        {
                            Code = "ros",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ruins of Symbaroum source material",
                            DocumentationLink = "https://freeleaguepublishing.com/games/ruins-of-symbaroum/",
                            IsActive = true,
                            License = "https://opengamingfoundation.org/ogl.html",
                            Name = "Ruins of Symbaroum"
                        });
                });

            modelBuilder.Entity("Chronicis.Shared.Models.SummaryTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("IsSystem");

                    b.HasIndex("WorldId");

                    b.ToTable("SummaryTemplates");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Auth0UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("HasCompletedOnboarding")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Auth0UserId")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicSlug")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("PublicSlug")
                        .IsUnique()
                        .HasDatabaseName("IX_Worlds_PublicSlug")
                        .HasFilter("[PublicSlug] IS NOT NULL");

                    b.HasIndex("OwnerId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Worlds_OwnerId_Slug");

                    b.ToTable("Worlds");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("IX_WorldDocuments_ArticleId")
                        .HasFilter("[ArticleId] IS NOT NULL");

                    b.HasIndex("UploadedById");

                    b.HasIndex("WorldId");

                    b.ToTable("WorldDocuments");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("WorldId", "IsActive");

                    b.ToTable("WorldInvitations");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("WorldLinks");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("UserId");

                    b.HasIndex("WorldId", "UserId")
                        .IsUnique();

                    b.ToTable("WorldMembers");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldResourceProvider", b =>
                {
                    b.Property<Guid>("WorldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResourceProviderCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ModifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WorldId", "ResourceProviderCode");

                    b.HasIndex("ResourceProviderCode");

                    b.HasIndex("WorldId");

                    b.ToTable("WorldResourceProviders");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Arc", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Campaign", "Campaign")
                        .WithMany("Arcs")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedArcs")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.SummaryTemplate", "SummaryTemplate")
                        .WithMany()
                        .HasForeignKey("SummaryTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Campaign");

                    b.Navigation("Creator");

                    b.Navigation("SummaryTemplate");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Article", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Arc", "Arc")
                        .WithMany("Sessions")
                        .HasForeignKey("ArcId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.Campaign", "Campaign")
                        .WithMany("Articles")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedArticles")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.User", "Modifier")
                        .WithMany("ModifiedArticles")
                        .HasForeignKey("LastModifiedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.Article", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.User", "Player")
                        .WithMany("OwnedCharacters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.SummaryTemplate", "SummaryTemplate")
                        .WithMany()
                        .HasForeignKey("SummaryTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Articles")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Arc");

                    b.Navigation("Campaign");

                    b.Navigation("Creator");

                    b.Navigation("Modifier");

                    b.Navigation("Parent");

                    b.Navigation("Player");

                    b.Navigation("SummaryTemplate");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleAlias", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Article", "Article")
                        .WithMany("Aliases")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleExternalLink", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Article", "Article")
                        .WithMany("ExternalLinks")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ArticleLink", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Article", "SourceArticle")
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("SourceArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.Article", "TargetArticle")
                        .WithMany("IncomingLinks")
                        .HasForeignKey("TargetArticleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SourceArticle");

                    b.Navigation("TargetArticle");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Campaign", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Owner")
                        .WithMany("OwnedCampaigns")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.SummaryTemplate", "SummaryTemplate")
                        .WithMany()
                        .HasForeignKey("SummaryTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Campaigns")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("SummaryTemplate");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Quest", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Arc", "Arc")
                        .WithMany()
                        .HasForeignKey("ArcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedQuests")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Arc");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.QuestUpdate", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedQuestUpdates")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.Quest", "Quest")
                        .WithMany("Updates")
                        .HasForeignKey("QuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.Article", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");

                    b.Navigation("Quest");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.SummaryTemplate", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Creator");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.World", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Owner")
                        .WithMany("OwnedWorlds")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldDocument", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.Article", "Article")
                        .WithMany("Images")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Chronicis.Shared.Models.User", "UploadedBy")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Documents")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("UploadedBy");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldInvitation", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Creator")
                        .WithMany("CreatedInvitations")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Invitations")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldLink", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Links")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldMember", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.User", "Inviter")
                        .WithMany("InvitedMembers")
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Chronicis.Shared.Models.User", "User")
                        .WithMany("WorldMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("Members")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inviter");

                    b.Navigation("User");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.WorldResourceProvider", b =>
                {
                    b.HasOne("Chronicis.Shared.Models.ResourceProvider", "ResourceProvider")
                        .WithMany("WorldResourceProviders")
                        .HasForeignKey("ResourceProviderCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chronicis.Shared.Models.World", "World")
                        .WithMany("WorldResourceProviders")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceProvider");

                    b.Navigation("World");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Arc", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Article", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Children");

                    b.Navigation("ExternalLinks");

                    b.Navigation("Images");

                    b.Navigation("IncomingLinks");

                    b.Navigation("OutgoingLinks");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Campaign", b =>
                {
                    b.Navigation("Arcs");

                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.Quest", b =>
                {
                    b.Navigation("Updates");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.ResourceProvider", b =>
                {
                    b.Navigation("WorldResourceProviders");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.User", b =>
                {
                    b.Navigation("CreatedArcs");

                    b.Navigation("CreatedArticles");

                    b.Navigation("CreatedInvitations");

                    b.Navigation("CreatedQuestUpdates");

                    b.Navigation("CreatedQuests");

                    b.Navigation("InvitedMembers");

                    b.Navigation("ModifiedArticles");

                    b.Navigation("OwnedCampaigns");

                    b.Navigation("OwnedCharacters");

                    b.Navigation("OwnedWorlds");

                    b.Navigation("UploadedDocuments");

                    b.Navigation("WorldMemberships");
                });

            modelBuilder.Entity("Chronicis.Shared.Models.World", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Campaigns");

                    b.Navigation("Documents");

                    b.Navigation("Invitations");

                    b.Navigation("Links");

                    b.Navigation("Members");

                    b.Navigation("WorldResourceProviders");
                });
#pragma warning restore 612, 618
        }
    }
}
