# .github/workflows/deploy.yml
name: Deploy Chronicis Placeholder

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: chronicis
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
